version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 10
  reviewers:
  - trylovetom
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.19
    - 14.14.22
    - 14.14.31
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.11.1
    - 4.14.2
    - 4.16.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.4.0
    - 7.5.0
    - 7.6.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.11.1
    - 4.14.2
    - 4.16.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
    - 26.0.20
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
